name: Build and Deploy to EC2

on:
  push:
    branches:
      - master

concurrency: deployment

jobs:
  build-and-deploy:
    name: Build and Deploy Docker Image to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: us-west-2

    - name: Log into Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'false'

    - name: Get Current Timestamp
      id: date
      run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d_%H-%M-%S')"

    - name: Build and Push the Docker image
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPO: mindfullstack-prd
        IMAGE_TAG: ${{ steps.date.outputs.timestamp }}
      run: |
        docker build ./ --file ./Dockerfile --tag $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG"

    - name: SSH into EC2 and Pull Docker Image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}               #figure out once terraform apply is completed successfully.
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ steps.build-image.outputs.image }}
          docker stop mindfullstack || true
          docker rm mindfullstack || true
          docker run -d -p 8080:8080 --name mindfullstack ${{ steps.build-image.outputs.image }}